### ISSUE TITLE
ModuleNotFoundError: No module named 'twitter'

### ISSUE THREAD

**Issue by mrded** [samhector/InkyTwitterTrends#1]
Hi, thanks for a great module!

Looks like there are dependencies missing. I will be nice to have a `requirements.txt` file.

```
» ./trends.py
Traceback (most recent call last):
  File "./trends.py", line 14, in <module>
    from twitter import *
ModuleNotFoundError: No module named 'twitter'
```

**Comment by mrded** [comment]
I made a PR here https://github.com/samhector/InkyTwitterTrends/pull/2

**Comment by samhector** [comment]
Merged!
